[workspace]
members = [
    "peerage-merkle-tree",
    "peerage-crypto",
    "peerage-hash",
    "peerage-utils",
    "peerage-binary",
    "peerage-bptree",
    "peerage-macros",
    "peerage-holder",
    "peerage-ledger"
]